export const GETBOOTCAMP = 'GETBOOTCAMP';
export const SETLOADING = 'SETLOADING';
export const BOOTCAMPERROR = 'BOOTCAMPERROR';
export const SETPARAMS = 'SETPARAMS';
export const REMOVEPARAMS = 'REMOVEPARAMS';
export const SETCURRENT = 'SETCURRENT';
export const CLEARCURRENT = 'CLEARCURRENT';

export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const UPDATEUSER = 'UPDATEUSER';

export const GETCOURSES = 'GETCOURSES';
export const DELETECOURSE = 'DELETECOURSE';
export const ADDCOURSE = 'ADDCOURSE';
export const UPDATECOURSE = 'UPDATECOURSE';
export const COURSEERROR = 'COURSEERROR';
export const COURSELOADING = 'COURSELOADING';

export const GETREVIEWS = 'GETREVIEWS';
export const DELETEREVIEW = 'DELETEREVIEW';
export const UPDATEREVIEW = 'UPDATEREVIEW';
export const SETCURRENTREVIEW = 'SETCURRENTREVIEW';
export const CLEARCURRENTREVIEW = 'CLEARCURRENTREVIEW';
export const REVIEWERROR = 'REVIEWERROR';
export const REVIEWLOADING = 'REVIEWLOADING';
